package com.rvk.studio.engine.project

import android.content.Context
import com.rvk.studio.storage.StorageManager
import java.io.File

enum class ProjectPlatform {
    ANDROID_KOTLIN,
    ANDROID_JAVA,
    PYTHON,
    REACT_NATIVE,
    CPP,
    FLUTTER
}

data class ProjectConfig(
    val name: String,
    val platform: ProjectPlatform,
    val packageName: String = "com.example.${name.lowercase().replace(Regex("[^a-z0-9]"), "")}",
    val minSdk: Int = 24,
    val targetSdk: Int = 34,
    val saveLocation: String = ""
)

class ProjectCreator(private val context: Context) {

    fun createProject(config: ProjectConfig): File {
        val projectDir = if (config.saveLocation.isNotEmpty()) {
            File(config.saveLocation, config.name)
        } else {
            File(StorageManager.getProjectsDir(context), config.name)
        }

        projectDir.mkdirs()

        return when (config.platform) {
            ProjectPlatform.ANDROID_KOTLIN -> createAndroidProject(projectDir, config, "kotlin")
            ProjectPlatform.ANDROID_JAVA -> createAndroidProject(projectDir, config, "java")
            ProjectPlatform.PYTHON -> createPythonProject(projectDir, config)
            ProjectPlatform.REACT_NATIVE -> createReactNativeProject(projectDir, config)
            ProjectPlatform.CPP -> createCppProject(projectDir, config)
            ProjectPlatform.FLUTTER -> createFlutterProject(projectDir, config)
        }
    }

    private fun createAndroidProject(projectDir: File, config: ProjectConfig, language: String): File {
        // Root build.gradle.kts
        File(projectDir, "build.gradle.kts").writeText("""
plugins {
    id("com.android.application") version "8.2.2" apply false
    ${if (language == "kotlin") """id("org.jetbrains.kotlin.android") version "1.9.22" apply false""" else ""}
}

tasks.register("clean", Delete::class) {
    delete(rootProject.layout.buildDirectory)
}
""".trimIndent())

        // settings.gradle.kts
        File(projectDir, "settings.gradle.kts").writeText("""
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolution {
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "${config.name}"
include(":app")
""".trimIndent())

        // gradle.properties
        File(projectDir, "gradle.properties").writeText("""
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
""".trimIndent())

        // gradle wrapper properties
        val wrapperDir = File(projectDir, "gradle/wrapper")
        wrapperDir.mkdirs()
        File(wrapperDir, "gradle-wrapper.properties").writeText("""
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.5-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
""".trimIndent())

        // gradlew script
        val gradlewFile = File(projectDir, "gradlew")
        gradlewFile.writeText("""#!/bin/sh
# Gradle start up script for POSIX generated by Android Studio Mobile
APP_NAME="Gradle"
APP_BASE_NAME=${'$'}{0##*/}
DEFAULT_JVM_OPTS='"-Xmx2048m" "-Xms256m"'

# Resolve JAVA_HOME
if [ -z "${'$'}JAVA_HOME" ]; then
    JAVACMD="java"
else
    JAVACMD="${'$'}JAVA_HOME/bin/java"
fi

# Resolve project directory
PRG="${'$'}0"
while [ -h "${'$'}PRG" ]; do
    ls=${'$'}(ls -ld "${'$'}PRG")
    link=${'$'}(expr "${'$'}ls" : '.*-> \(.*\)${'$'}')
    if expr "${'$'}link" : '/.*' > /dev/null; then
        PRG="${'$'}link"
    else
        PRG=${'$'}(dirname "${'$'}PRG")/"${'$'}link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"${'$'}PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "${'$'}SAVED" >/dev/null

CLASSPATH=${'$'}APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "${'$'}JAVACMD" ${'$'}DEFAULT_JVM_OPTS \
    -classpath "${'$'}CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "${'$'}@"
""".trimIndent())
        gradlewFile.setExecutable(true, false)

        // app/build.gradle.kts
        val appDir = File(projectDir, "app")
        appDir.mkdirs()

        File(appDir, "build.gradle.kts").writeText("""
plugins {
    id("com.android.application")
    ${if (language == "kotlin") """id("org.jetbrains.kotlin.android")""" else ""}
}

android {
    namespace = "${config.packageName}"
    compileSdk = ${config.targetSdk}

    defaultConfig {
        applicationId = "${config.packageName}"
        minSdk = ${config.minSdk}
        targetSdk = ${config.targetSdk}
        versionCode = 1
        versionName = "1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    ${if (language == "kotlin") """
    kotlinOptions {
        jvmTarget = "17"
    }""" else ""}
}

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
}
""".trimIndent())

        // proguard-rules.pro
        File(appDir, "proguard-rules.pro").writeText("# Add project specific ProGuard rules here.\n")

        // AndroidManifest.xml
        val mainDir = File(appDir, "src/main")
        mainDir.mkdirs()
        File(mainDir, "AndroidManifest.xml").writeText("""
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:label="${config.name}"
        android:supportsRtl="true"
        android:theme="@style/Theme.Material3.DayNight.NoActionBar">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
""".trimIndent())

        // Source files
        val packagePath = config.packageName.replace(".", "/")
        val srcDir = if (language == "kotlin") {
            File(mainDir, "java/$packagePath")
        } else {
            File(mainDir, "java/$packagePath")
        }
        srcDir.mkdirs()

        if (language == "kotlin") {
            File(srcDir, "MainActivity.kt").writeText("""
package ${config.packageName}

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}
""".trimIndent())
        } else {
            File(srcDir, "MainActivity.java").writeText("""
package ${config.packageName};

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}
""".trimIndent())
        }

        // Resources
        val resDir = File(mainDir, "res")
        val layoutDir = File(resDir, "layout")
        layoutDir.mkdirs()
        val valuesDir = File(resDir, "values")
        valuesDir.mkdirs()

        File(layoutDir, "activity_main.xml").writeText("""
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:textSize="24sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
""".trimIndent())

        File(valuesDir, "strings.xml").writeText("""
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${config.name}</string>
</resources>
""".trimIndent())

        File(valuesDir, "themes.xml").writeText("""
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.${config.name.replace(Regex("[^a-zA-Z0-9]"), "")}" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        <item name="colorPrimary">#FF6200EE</item>
        <item name="colorPrimaryVariant">#FF3700B3</item>
        <item name="colorOnPrimary">#FFFFFFFF</item>
    </style>
</resources>
""".trimIndent())

        return projectDir
    }

    private fun createPythonProject(projectDir: File, config: ProjectConfig): File {
        File(projectDir, "main.py").writeText("""
#!/usr/bin/env python3
\"\"\"${config.name} - Python Project\"\"\"

def main():
    print("Hello from ${config.name}!")

if __name__ == "__main__":
    main()
""".trimIndent())

        File(projectDir, "requirements.txt").writeText("")

        File(projectDir, "README.md").writeText("""
# ${config.name}

A Python project created with Android Studio Mobile.

## Getting Started

```bash
python main.py
```
""".trimIndent())

        val srcDir = File(projectDir, "src")
        srcDir.mkdirs()
        File(srcDir, "__init__.py").writeText("")
        File(srcDir, "app.py").writeText("""
class App:
    def __init__(self):
        self.name = "${config.name}"

    def run(self):
        print(f"Running {self.name}")
""".trimIndent())

        val testsDir = File(projectDir, "tests")
        testsDir.mkdirs()
        File(testsDir, "__init__.py").writeText("")
        File(testsDir, "test_app.py").writeText("""
import unittest
from src.app import App

class TestApp(unittest.TestCase):
    def test_init(self):
        app = App()
        self.assertEqual(app.name, "${config.name}")

if __name__ == "__main__":
    unittest.main()
""".trimIndent())

        return projectDir
    }

    private fun createReactNativeProject(projectDir: File, config: ProjectConfig): File {
        File(projectDir, "package.json").writeText("""
{
  "name": "${config.name.lowercase().replace(Regex("[^a-z0-9]"), "-")}",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "metro-react-native-babel-preset": "0.76.8"
  }
}
""".trimIndent())

        File(projectDir, "index.js").writeText("""
import { AppRegistry } from 'react-native';
import App from './App';

AppRegistry.registerComponent('${config.name}', () => App);
""".trimIndent())

        File(projectDir, "App.js").writeText("""
import React from 'react';
import { SafeAreaView, StyleSheet, Text, View } from 'react-native';

const App = () => {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.content}>
        <Text style={styles.title}>${config.name}</Text>
        <Text style={styles.subtitle}>Welcome to React Native!</Text>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  content: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 8 },
  subtitle: { fontSize: 16, color: '#666' },
});

export default App;
""".trimIndent())

        File(projectDir, "babel.config.js").writeText("""
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
""".trimIndent())

        return projectDir
    }

    private fun createCppProject(projectDir: File, config: ProjectConfig): File {
        val srcDir = File(projectDir, "src")
        srcDir.mkdirs()
        val includeDir = File(projectDir, "include")
        includeDir.mkdirs()
        val buildDir = File(projectDir, "build")
        buildDir.mkdirs()

        File(projectDir, "CMakeLists.txt").writeText("""
cmake_minimum_required(VERSION 3.10)
project(${config.name} VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(include)

add_executable(${'$'}{PROJECT_NAME} src/main.cpp)
""".trimIndent())

        File(includeDir, "app.h").writeText("""
#ifndef APP_H
#define APP_H

#include <string>

class App {
public:
    App(const std::string& name);
    void run();
    std::string getName() const;

private:
    std::string m_name;
};

#endif // APP_H
""".trimIndent())

        File(srcDir, "main.cpp").writeText("""
#include <iostream>
#include "app.h"

int main() {
    App app("${config.name}");
    app.run();
    return 0;
}

App::App(const std::string& name) : m_name(name) {}

void App::run() {
    std::cout << "Hello from " << m_name << "!" << std::endl;
}

std::string App::getName() const {
    return m_name;
}
""".trimIndent())

        File(projectDir, "Makefile").writeText("""
CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -Iinclude
BUILD_DIR = build
SRC = src/main.cpp

all: ${'$'}(BUILD_DIR)/${config.name}

${'$'}(BUILD_DIR)/${config.name}: ${'$'}(SRC)
	${'$'}(CXX) ${'$'}(CXXFLAGS) -o ${'$'}@ ${'$'}^

clean:
	rm -rf ${'$'}(BUILD_DIR)/*

.PHONY: all clean
""".trimIndent())

        return projectDir
    }

    private fun createFlutterProject(projectDir: File, config: ProjectConfig): File {
        File(projectDir, "pubspec.yaml").writeText("""
name: ${config.name.lowercase().replace(Regex("[^a-z0-9]"), "_")}
description: A Flutter project created with Android Studio Mobile.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
""".trimIndent())

        val libDir = File(projectDir, "lib")
        libDir.mkdirs()

        File(libDir, "main.dart").writeText("""
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${config.name}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: '${config.name}'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '\${'$'}_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
""".trimIndent())

        // Android directory for Flutter
        val androidDir = File(projectDir, "android")
        androidDir.mkdirs()
        File(androidDir, "build.gradle").writeText("""
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
""".trimIndent())

        val testDir = File(projectDir, "test")
        testDir.mkdirs()
        File(testDir, "widget_test.dart").writeText("""
import 'package:flutter_test/flutter_test.dart';
import 'package:${config.name.lowercase().replace(Regex("[^a-z0-9]"), "_")}/main.dart';

void main() {
  testWidgets('Counter increments test', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());
    expect(find.text('0'), findsOneWidget);
    await tester.tap(find.byTooltip('Increment'));
    await tester.pump();
    expect(find.text('1'), findsOneWidget);
  });
}
""".trimIndent())

        return projectDir
    }
}
